baseURL = "/"
languageCode = "en-us"
title = "Internet Creeps"
theme = "hugograyscale-master"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # Provide some metadata for search and indexing services
    description = "Internet Creeps is a collection of 222 NFTs exclusively on the Internet Computer."

[Author]
    name = "InternetCreeps"
    email = ""

[Social]
    twitter = "internet_creeps"
    distrikt = "internet_creeps"
